version: '3'

services:

  mongo:
    restart: unless-stopped
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=<username>
      - MONGO_INITDB_ROOT_PASSWORD=<password>
      - MONGO_INITDB_DATABASE=auth
    volumes:
      - ./db/mongo-db:/data/db
    networks:
      - dgray-network

  server:
    container_name: server
    # hostname: server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
      # args:
      #   NODE_ENV: production
    ports:
      - "4021:3001"
    # volumes:
    #   - ./server:/app
    #   - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3001 # MUST match with External port above ^
      - DATABASE_URI=mongo # match with mongo container_name
      - DATABASE_PORT=27017 # match with mongo container
      - MONGO_USER=<username> # match with mongo container
      - MONGO_PASS=<password> # match with mongo container
      - MONGODB_COLLECTION=dgrayCollection
      - REFRESH_TOKEN_SECRET=<secrethash>
      - ACCESS_TOKEN_SECRET=<secrethash>
      - FRONTEND_URL_ORIGIN=https://nodeadmin.williamusic.com
      - FRONTEND_URL_PORT=443 # if using SSL = 443
    depends_on:
      - mongo
    networks:
      - dgray-network

  # nginx:
  #   restart: always
  #   depends_on:
  #     - server
  #     - client
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 4012:80
  #   networks:
  #     - dgray-network

  # nginx built inside
  client:
    container_name: dgray-client
    # hostname: dgray-client
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile
      # args:
      #   NODE_ENV: production
    # volumes:
    #   - ./client:/app
    #   - /app/node_modules
    ports:
      - 4020:80 # because nginx is inside this container too
    environment:
      - REACT_APP__API_IP=https://api.williamusic.com
      - REACT_APP__API_PORT=443 # MUST match API external port. use 433 if https://
    depends_on:
      - server
    networks:
      - dgray-network
      # add to ngnix-prox-mgmt network

networks:
  dgray-network:
    driver: bridge

volumes:
  mongo-db:
