version: '3'

services:

  mongo:
    restart: unless-stopped
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mymongouser
      - MONGO_INITDB_ROOT_PASSWORD=mypassword
      - MONGO_INITDB_DATABASE=auth
    volumes:
      - ./db/mongo-db:/data/db
    networks:
      - dgray-network
  
  mongo-express:
    image: mongo-express
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=27017
      # - ME_CONFIG_MONGODB_ENABLE_ADMIN=false
      # - ME_CONFIG_MONGODB_AUTH_USERNAME=admin #match with mongo container
      # - ME_CONFIG_MONGODB_AUTH_PASSWORD=mypassword #match with mongo container
      # - ME_CONFIG_BASICAUTH_USERNAME=admin #match with mongo container
      # - ME_CONFIG_BASICAUTH_PASSWORD=myMongoExpPass #match with mongo container
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mymongouser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=mypassword
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=expressful
    ports:
      - "3002:8081"
    volumes:
      - ./db/mongo-db:/data/db
    depends_on:
      - server
    networks:
      - dgray-network

  server:
    container_name: server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    ports:
      - "3001:3001"
    volumes:
      - ./server:/app
      - /app/node_modules
    environment:
      - PORT=3001 # MUST match with External port above ^
      - DATABASE_URI=mongo #match with mongo container_name
      - DATABASE_PORT=27017 #match with mongo container
      - MONGO_USER=localhost #match with mongo container unless localhost
      - MONGO_PASS=mypassword #match with mongo container
      - MONGODB_COLLECTION=dgrayCollection
      - REFRESH_TOKEN_SECRET=myRefreshTokenSecret
      - ACCESS_TOKEN_SECRET=myAccessTokenSecret
      - FRONTEND_URL_ORIGIN=http://localhost:3000
    depends_on:
      - mongo
    networks:
      - dgray-network

      
  # # # TODO stop building nginx inside of client container
  # nginx:
  #   restart: always
  #   depends_on:
  #     - server
  #     - client
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 4012:80
  #   networks:
  #     - dgray-network

  client:
    container_name: client
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile.dev
      args:
        NODE_ENV: development
    volumes:
      - ./client:/app
      - /app/node_modules
    ports:
      - 3000:3000
    environment:
      - REACT_APP__API_IP=http://localhost # any react env must start with REACT_APP_
      - REACT_APP__API_PORT=3001 # MUST match API external port
    depends_on:
      - server
    networks:
      - dgray-network

networks:
  dgray-network:
    driver: bridge

volumes:
  mongo-db:
