version: '3'

services:

  mongo:
    restart: unless-stopped
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=myMongoUser
      - MONGO_INITDB_ROOT_PASSWORD=myMongoPassword
      - MONGO_INITDB_DATABASE=auth
    volumes:
      - ./db/mongo-db:/data/db
    networks:
      - dgray-network

  server:
    container_name: server
    # hostname: server
    restart: unless-stopped
    build:
      context: ./server
      dockerfile: Dockerfile
      # args:
      #   NODE_ENV: production
    ports:
      - "4021:3001"
    # volumes:
    #   - ./server:/app
    #   - /app/node_modules
    environment:
      - NODE_ENV=production
      - PORT=3001 # MUST match with External port above ^
      - DATABASE_URI=mongo # match with mongo container_name
      - DATABASE_PORT=27017 # match with mongo container
      - MONGO_USER=myMongoUser # match with mongo container
      - MONGO_PASS=myMongoPassword # match with mongo container
      - MONGODB_COLLECTION=dgrayCollection
      - REFRESH_TOKEN_SECRET=bdfb34h5n56h5v45b^v4v34b*b345b3s(eb
      - ACCESS_TOKEN_SECRET=23v234b68m679,*vQWV3#W345N%GDF&*23BG
      - FRONTEND_URL_ORIGIN=https://nodeadmin.williamusic.com
      - FRONTEND_URL_PORT=443 # if using SSL = 443
    depends_on:
      - mongo
    networks:
      - dgray-network

  # nginx:
  #   restart: always
  #   depends_on:
  #     - server
  #     - client
  #   build:
  #     context: ./nginx
  #     dockerfile: Dockerfile.dev
  #   ports:
  #     - 4012:80
  #   networks:
  #     - dgray-network

  # nginx built inside
  client:
    container_name: dgray-client
    # hostname: dgray-client
    restart: unless-stopped
    build:
      context: ./client
      dockerfile: Dockerfile
      # args:
      #   NODE_ENV: production
    # volumes:
    #   - ./client:/app
    #   - /app/node_modules
    ports:
      - 4020:80 # because nginx is inside this container too
    environment:
      - REACT_APP__API_IP=https://nodeadmin.williamusic.com # Nginx Prox Mgmt does not lie "_" in domain
      - REACT_APP__API_PORT=443 # MUST match API external port. use 433 if https://
      - REACT_APP__API_FOLDER=/api
    depends_on:
      - server
    networks:
      - dgray-network
      # add to ngnix-prox-mgmt network

networks:
  dgray-network:
    driver: bridge

volumes:
  mongo-db:
